import {
    Users, UserPlus, FolderTree, Database, FileSignature, Package, Map, List, Ban, Briefcase, CreditCard, FileSpreadsheet, Receipt, ShoppingBag, Calculator, Boxes, DollarSign
} from 'lucide-react';
import { contabilidadRoutes } from '../../Pages/Contabilidad/contabilidadRoutes';

export const DASHBOARD_MODULE_CARDS = [
    {
        id: 'card_contabilidad',
        titulo: 'Contabilidad',
        subtitulo: 'Pedidos, comisiones y utilidad Bellaroma.',
        permiso: 'contabilidad.ver',
        href: () => contabilidadRoutes.index(),
        icon: Calculator,
        borderClass: 'border-teal-500/20',
        iconWrapClass: 'bg-teal-500/10 border-teal-500/20',
        iconClass: 'text-teal-500',
    },
    {
        id: 'card_auto_cobranza',
        titulo: 'Credibox',
        subtitulo: 'Control de crédito y cobros.',
        permiso: 'cobranza.ver',
        href: () => route('auto-cobranza.index'),
        icon: CreditCard,
        borderClass: 'border-red-500/20',
        iconWrapClass: 'bg-red-500/10 border-red-500/20',
        iconClass: 'text-red-500',
    },
    {
        id: 'card_usuarios',
        titulo: 'Control de Usuarios',
        subtitulo: 'Administrar roles y personal.',
        permiso: 'usuarios.gestionar',
        href: () => route('admin.usuarios'),
        icon: Users,
        borderClass: '',
        borderStyle: { borderColor: 'var(--color-primario)' },
        iconWrapClass: '',
        iconWrapStyle: { backgroundColor: 'color-mix(in srgb, var(--color-primario) 15%, transparent)' },
        iconClass: '',
        iconStyle: { color: 'var(--color-primario)' },
    },
    {
        id: 'card_enlaces',
        titulo: 'Generar Accesos',
        subtitulo: 'Crear enlaces seguros.',
        permiso: 'usuarios.generar_permisos',
        href: () => route('admin.enlaces'),
        icon: UserPlus,
        borderClass: 'theme-border',
        iconWrapClass: 'theme-element theme-border',
        iconClass: 'theme-text-main',
    },
    {
        id: 'card_catalogos',
        titulo: 'Catálogos Centrales',
        subtitulo: 'Procesos y comisiones.',
        permiso: 'catalogos.gestionar',
        href: () => route('admin.catalogos'),
        icon: FolderTree,
        borderClass: 'border-blue-500/20',
        iconWrapClass: 'bg-blue-500/10 border-blue-500/20',
        iconClass: 'text-blue-500',
    },
    {
        id: 'card_clientes_bd',
        titulo: 'Base de Clientes',
        subtitulo: 'Sincronización Wizerp.',
        permiso: 'clientes.ver',
        href: () => route('admin.clientes'),
        icon: Database,
        borderClass: 'border-emerald-500/20',
        iconWrapClass: 'bg-emerald-500/10 border-emerald-500/20',
        iconClass: 'text-emerald-500',
    },
    {
        id: 'card_solicitudes',
        titulo: 'Panel Solicitudes',
        subtitulo: 'Procesos financieros TAG.',
        permiso: 'solicitudes.ver_listado',
        href: () => route('solicitudes.index'),
        icon: FileSignature,
        borderClass: 'border-amber-500/20',
        iconWrapClass: 'bg-amber-500/10 border-amber-500/20',
        iconClass: 'text-amber-500',
    },
    {
        id: 'card_cancelaciones_cotizaciones',
        titulo: 'Cancel. y Cotizaciones',
        subtitulo: 'Remisión, pedido y cotización.',
        permiso: 'cancelaciones_cotizaciones.ver_listado',
        href: () => route('cancelaciones_cotizaciones.index'),
        icon: Ban,
        borderClass: 'border-orange-500/20',
        iconWrapClass: 'bg-orange-500/10 border-orange-500/20',
        iconClass: 'text-orange-500',
    },
    {
        id: 'card_almacenes_productos',
        titulo: 'Productos',
        subtitulo: 'Catálogo maestro de productos.',
        permisoAny: ['almacenes.productos.ver', 'catalogos.gestionar'],
        href: () => route('almacenes.productos.index'),
        icon: Package,
        borderClass: 'border-amber-500/20',
        iconWrapClass: 'bg-amber-500/10 border-amber-500/20',
        iconClass: 'text-amber-500',
    },
    {
        id: 'card_almacenes_inventarios',
        titulo: 'Inventarios',
        subtitulo: 'Existencias y ubicaciones por almacén.',
        permisoAny: ['almacenes.inventarios.ver', 'catalogos.gestionar'],
        href: () => route('almacenes.inventarios.index'),
        icon: Boxes,
        borderClass: 'border-orange-500/20',
        iconWrapClass: 'bg-orange-500/10 border-orange-500/20',
        iconClass: 'text-orange-500',
    },
    {
        id: 'card_almacenes_costos',
        titulo: 'Costos',
        subtitulo: 'Costos y precios por almacén.',
        permisoAny: ['almacenes.costos.ver', 'catalogos.gestionar'],
        href: () => route('almacenes.costos.index'),
        icon: DollarSign,
        borderClass: 'border-yellow-500/20',
        iconWrapClass: 'bg-yellow-500/10 border-yellow-500/20',
        iconClass: 'text-yellow-500',
    },
    {
        id: 'card_activos',
        titulo: 'Control de Activos',
        subtitulo: 'Inventario y mantenimiento.',
        permiso: 'activos.ver',
        href: () => route('activos.index'),
        icon: Package,
        borderClass: 'border-emerald-500/20',
        iconWrapClass: 'bg-emerald-500/10 border-emerald-500/20',
        iconClass: 'text-emerald-500',
    },
    {
        id: 'card_rh',
        titulo: 'Recursos Humanos',
        subtitulo: 'Dashboard, colaboradores y horas extra.',
        permiso: 'rh.ver',
        href: () => route('rh.index'),
        icon: Briefcase,
        borderClass: 'border-rose-500/20',
        iconWrapClass: 'bg-rose-500/10 border-rose-500/20',
        iconClass: 'text-rose-500',
    },
    {
        id: 'card_clientes',
        titulo: 'Mis Clientes',
        subtitulo: 'Cartera y altas rápidas.',
        permiso: 'mis_clientes.gestionar',
        href: () => route('mis_clientes.index'),
        icon: Users,
        borderClass: 'border-purple-500/20',
        iconWrapClass: 'bg-purple-500/10 border-purple-500/20',
        iconClass: 'text-purple-500',
    },
    {
        id: 'card_entregas',
        titulo: 'Área Logística',
        subtitulo: 'Cotizador y envíos.',
        permiso: 'entregas.cotizar',
        href: () => route('entregas.index'),
        icon: Map,
        borderClass: 'border-indigo-500/20',
        iconWrapClass: 'bg-indigo-500/10 border-indigo-500/20',
        iconClass: 'text-indigo-500',
    },
    {
        id: 'card_plantilla_bellaroma',
        titulo: 'Plantilla Pedidos',
        subtitulo: 'Generación de lista de precios.',
        permiso: 'plantilla_pedidos.ver',
        href: () => route('plantilla_bellaroma.index'),
        icon: FileSpreadsheet,
        borderClass: '',
        borderStyle: { borderColor: 'var(--color-primario)' },
        iconWrapClass: '',
        iconWrapStyle: { backgroundColor: 'color-mix(in srgb, var(--color-primario) 15%, transparent)' },
        iconClass: '',
        iconStyle: { color: 'var(--color-primario)' },
    },
    {
        id: 'card_woocommerce',
        titulo: 'Sincronizar Precios',
        subtitulo: 'WooCommerce y catálogo Bellaroma.',
        permiso: 'woocommerce.ver',
        href: () => route('woocommerce.index'),
        icon: ShoppingBag,
        borderClass: 'border-violet-500/20',
        iconWrapClass: 'bg-violet-500/10 border-violet-500/20',
        iconClass: 'text-violet-500',
    },
    {
        id: 'card_facturas',
        titulo: 'Facturación',
        subtitulo: 'Generación y control de facturas.',
        permiso: 'facturas.ver_listado',
        href: () => route('facturas.index'),
        icon: Receipt,
        borderClass: 'border-cyan-500/20',
        iconWrapClass: 'bg-cyan-500/10 border-cyan-500/20',
        iconClass: 'text-cyan-500',
    },
];

export const DASHBOARD_FUNCTION_CARDS = [
    {
        id: 'func_listados',
        titulo: 'Generador de Listados',
        subtitulo: 'Crea y administra listados personalizados.',
        permiso: 'listados.ver',
        href: () => route('listados.index'),
        icon: List,
        borderClass: 'border-emerald-500/20',
        iconWrapClass: 'bg-emerald-500/10 border-emerald-500/20',
        iconClass: 'text-emerald-500',
    },
    {
        id: 'func_limpieza_clientes',
        titulo: 'Limpieza de Clientes',
        subtitulo: 'Corrección de codificación Wizerp.',
        permiso: 'funciones.limpieza_clientes',
        href: () => route('funciones.limpieza-clientes.index'),
        icon: Database,
        borderClass: 'border-blue-500/20',
        iconWrapClass: 'bg-blue-500/10 border-blue-500/20',
        iconClass: 'text-blue-500',
    },
    {
        id: 'func_ejercicio_escalonamiento',
        titulo: 'Ejercicio Escalonamiento',
        subtitulo: 'Simula proyecciones Plata · Oro · Diamante.',
        permiso: 'ejercicio_escalonamiento.ver',
        href: () => route('ejercicio_escalonamiento.index'),
        icon: Calculator,
        borderClass: 'border-violet-500/20',
        iconWrapClass: 'bg-violet-500/10 border-violet-500/20',
        iconClass: 'text-violet-500',
    },
    {
        id: 'func_asistencia',
        titulo: 'Asistencia',
        subtitulo: 'Procesamiento de checadora.',
        permiso: 'funciones.asistencia',
        href: () => route('funciones.asistencia.index'),
        icon: Users,
        borderClass: 'border-amber-500/20',
        iconWrapClass: 'bg-amber-500/10 border-amber-500/20',
        iconClass: 'text-amber-500',
    },
    {
        id: 'func_avisos',
        titulo: 'Avisos Mercancía',
        subtitulo: 'Cruce automático de inventario.',
        permiso: 'funciones.avisos',
        href: () => route('funciones.avisos.index'),
        icon: FileSignature,
        borderClass: 'border-cyan-500/20',
        iconWrapClass: 'bg-cyan-500/10 border-cyan-500/20',
        iconClass: 'text-cyan-500',
    },
    {
        id: 'func_gastos',
        titulo: 'Depuración Gastos',
        subtitulo: 'Descarta artículos irrelevantes.',
        permiso: 'funciones.gastos',
        href: () => route('funciones.gastos.index'),
        icon: DollarSign,
        borderClass: 'border-green-500/20',
        iconWrapClass: 'bg-green-500/10 border-green-500/20',
        iconClass: 'text-green-500',
    },
    {
        id: 'func_limpieza_archivos',
        titulo: 'Limpieza Archivos',
        subtitulo: 'Remueve apóstrofes y formatos.',
        permiso: 'funciones.limpieza_archivos',
        href: () => route('funciones.limpieza_archivos.index'),
        icon: FileSpreadsheet,
        borderClass: 'border-blue-500/20',
        iconWrapClass: 'bg-blue-500/10 border-blue-500/20',
        iconClass: 'text-blue-500',
    },
    {
        id: 'func_transacciones',
        titulo: 'Depuración Transacciones',
        subtitulo: 'Limpia saltos de línea internos.',
        permiso: 'funciones.transacciones',
        href: () => route('funciones.transacciones.index'),
        icon: Receipt,
        borderClass: 'border-indigo-500/20',
        iconWrapClass: 'bg-indigo-500/10 border-indigo-500/20',
        iconClass: 'text-indigo-500',
    },
];
