export const IMPORTACION_CATALOGOS = {
    sucursales: {
        titulo: 'Importar Sucursales',
        rutaPlantilla: 'admin.catalogos.sucursales.plantilla_importacion',
        rutaImportar: 'admin.catalogos.sucursales.importar',
        columnas: [
            { key: 'codigo', label: 'codigo', requerido: true, nota: 'Clave única, máx. 20 caracteres' },
            { key: 'nombre', label: 'nombre', requerido: true },
            { key: 'activo', label: 'activo', requerido: false, nota: '1/0, si/no. Por defecto: activo' },
        ],
        notas: ['Si el código ya existe, se actualiza el registro.', 'Los nombres se guardan en MAYÚSCULAS.'],
    },
    tipos_almacen: {
        titulo: 'Importar Tipos de Almacén',
        rutaPlantilla: 'admin.catalogos.tipos_almacen.plantilla_importacion',
        rutaImportar: 'admin.catalogos.tipos_almacen.importar',
        columnas: [
            { key: 'nombre', label: 'nombre', requerido: true, nota: 'Nombre único del tipo' },
        ],
        notas: ['Si el nombre ya existe, se actualiza el registro.', 'Los nombres se guardan en MAYÚSCULAS.'],
    },
    marcas_producto: {
        titulo: 'Importar Marcas',
        rutaPlantilla: 'admin.catalogos.marcas_producto.plantilla_importacion',
        rutaImportar: 'admin.catalogos.marcas_producto.importar',
        columnas: [
            { key: 'nombre', label: 'nombre', requerido: true },
            { key: 'activo', label: 'activo', requerido: false, nota: '1/0, si/no. Por defecto: activo' },
        ],
        notas: ['Upsert por nombre (sin distinguir mayúsculas).', 'Los nombres se guardan en MAYÚSCULAS.'],
    },
    categorias_producto: {
        titulo: 'Importar Categorías',
        rutaPlantilla: 'admin.catalogos.categorias_producto.plantilla_importacion',
        rutaImportar: 'admin.catalogos.categorias_producto.importar',
        columnas: [
            { key: 'nombre', label: 'nombre', requerido: true },
        ],
        notas: ['Upsert por nombre (sin distinguir mayúsculas).', 'Los nombres se guardan en MAYÚSCULAS.'],
    },
    almacenes: {
        titulo: 'Importar Almacenes',
        rutaPlantilla: 'admin.catalogos.almacenes.plantilla_importacion',
        rutaImportar: 'admin.catalogos.almacenes.importar',
        columnas: [
            { key: 'codigo', label: 'codigo', requerido: true },
            { key: 'nombre', label: 'nombre', requerido: true },
            { key: 'sucursal_codigo', label: 'sucursal_codigo', requerido: false, nota: 'Debe existir en catálogo de sucursales' },
            { key: 'tipo_almacen', label: 'tipo_almacen', requerido: false, nota: 'Debe existir en tipos de almacén' },
            { key: 'activo', label: 'activo', requerido: false, nota: '1/0, si/no' },
        ],
        notas: [
            'Importa sucursales y tipos de almacén antes de importar almacenes.',
            'Filas con sucursal o tipo inexistente se omiten y se reportan en CSV descargable.',
            'Los nombres se guardan en MAYÚSCULAS.',
        ],
    },
    productos: {
        titulo: 'Importar Productos',
        rutaPlantilla: 'almacenes.productos.plantilla_importacion',
        rutaImportar: null,
        rutaPreview: 'almacenes.productos.import_preview',
        rutaIniciar: 'almacenes.productos.import_iniciar',
        wizard: true,
        requiereAlmacen: false,
        columnas: [
            { key: 'folio', label: 'Folio', requerido: false, nota: 'Número de folio existente; si se omite se genera uno nuevo' },
            { key: 'sku', label: 'SKU', requerido: true, nota: 'Sin ceros a la izquierda' },
            { key: 'descripcion', label: 'Descripción', requerido: true },
            { key: 'marca', label: 'Marca', requerido: false, nota: 'Debe existir previamente en catálogos; no se crea automáticamente' },
            { key: 'categoria', label: 'Categoría', requerido: false, nota: 'Debe existir previamente en catálogos; no se crea automáticamente' },
            { key: 'codigo_barras', label: 'Código de barras', requerido: false, nota: 'Si se omite, se usa el SKU' },
            { key: 'peso', label: 'Peso (kg)', requerido: false },
            { key: 'activo', label: 'Activo', requerido: false, nota: '1/0, si/no' },
        ],
        mapping: {
            folio: '', sku: '', descripcion: '', marca: '', categoria: '', codigo_barras: '', peso: '', activo: '',
        },
        labels: {
            folio: 'Folio',
            sku: 'SKU *',
            descripcion: 'Descripción *',
            marca: 'Marca',
            categoria: 'Categoría',
            codigo_barras: 'Código de barras',
            peso: 'Peso (kg)',
            activo: 'Activo',
        },
        required: ['sku', 'descripcion'],
        notas: [
            'Incluye el folio si el producto ya tiene uno asignado en tu sistema anterior.',
            'Marca y categoría deben existir previamente en catálogos; no se crean automáticamente.',
            'Descripción y textos se guardan en MAYÚSCULAS.',
            'Código de barras vacío → se usa el SKU.',
            'Errores por fila se reportan en CSV descargable; las demás filas válidas sí se importan.',
            'SKU existente actualiza el producto.',
        ],
    },
    inventarios: {
        titulo: 'Importar Inventario',
        rutaPlantilla: 'almacenes.inventarios.plantilla_importacion',
        rutaImportar: null,
        rutaPreview: 'almacenes.inventarios.import_preview',
        rutaIniciar: 'almacenes.inventarios.import_iniciar',
        wizard: true,
        requiereAlmacen: true,
        columnas: [
            { key: 'folio', label: 'Folio', requerido: false, nota: 'Conserva el folio del producto si ya existe' },
            { key: 'sku', label: 'SKU', requerido: true },
            { key: 'descripcion', label: 'Descripción', requerido: true },
            { key: 'categoria', label: 'Categoría', requerido: false, nota: 'Debe existir previamente en catálogos' },
            { key: 'marca', label: 'Marca', requerido: false, nota: 'Debe existir previamente en catálogos' },
            { key: 'existencia', label: 'Existencia', requerido: true },
            { key: 'costo', label: 'Costo', requerido: false },
            { key: 'costo_reposicion', label: 'Costo reposición', requerido: false },
            { key: 'precio_venta', label: 'Precio venta', requerido: false },
        ],
        mapping: {
            folio: '', sku: '', descripcion: '', categoria: '', marca: '', existencia: '', costo: '', costo_reposicion: '', precio_venta: '',
        },
        labels: {
            folio: 'Folio',
            sku: 'SKU del Producto *',
            descripcion: 'Descripción *',
            categoria: 'Categoría',
            marca: 'Marca',
            existencia: 'Existencia *',
            costo: 'Costo',
            costo_reposicion: 'Costo Reposición',
            precio_venta: 'Precio Venta',
        },
        required: ['sku', 'descripcion', 'existencia'],
        notas: [
            'Selecciona el almacén destino antes de subir el archivo.',
            'Incluye el folio para conservar la numeración de productos existentes.',
            'Marca y categoría deben existir previamente en catálogos; no se crean automáticamente.',
            'Descripción y textos se guardan en MAYÚSCULAS.',
            'Código de barras vacío → se usa el SKU.',
            'Errores por fila se reportan en CSV descargable.',
            'Se importan productos, existencias y costos (si se mapean).',
        ],
    },
    costos: {
        titulo: 'Importar Costos y Precios',
        rutaPlantilla: 'almacenes.costos.plantilla_importacion',
        rutaImportar: null,
        rutaPreview: 'almacenes.costos.import_preview',
        rutaIniciar: 'almacenes.costos.import_iniciar',
        wizard: true,
        requiereAlmacen: true,
        columnas: [
            { key: 'sku', label: 'SKU', requerido: true },
            { key: 'costo', label: 'Costo', requerido: false },
            { key: 'costo_reposicion', label: 'Costo reposición', requerido: false },
            { key: 'precio_venta', label: 'Precio venta', requerido: false },
        ],
        mapping: {
            sku: '', costo: '', costo_reposicion: '', precio_venta: '',
        },
        labels: {
            sku: 'SKU *',
            costo: 'Costo',
            costo_reposicion: 'Costo Reposición',
            precio_venta: 'Precio Venta',
        },
        required: ['sku'],
        notas: [
            'Selecciona el almacén destino antes de subir el archivo.',
            'El SKU debe existir previamente en el catálogo de productos.',
            'Indica al menos uno: costo, costo de reposición o precio de venta.',
            'No modifica existencias de inventario.',
            'Errores por fila se reportan en CSV descargable.',
        ],
    },
};
