<?php

namespace App\Http\Requests\ControlPedidos;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

abstract class PedidoBmaRequestBase extends FormRequest
{
    protected function reglasComunes(): array
    {
        return [
            'cliente_id' => ['nullable', 'exists:clientes,id'],
            'origen_id' => ['nullable', 'exists:origenes_pedido,id'],
            'tipo_operacion_envio_id' => ['nullable', 'exists:catalogo_tipos_operacion_envio,id'],
            'numero_cliente' => ['nullable', 'string', 'max:50'],
            'folio_remision' => ['nullable', 'string', 'max:100'],
            'fecha' => ['nullable', 'date'],
            'almacen_id' => ['nullable', 'exists:almacenes,id'],
            'catalogo_banco_id' => ['nullable', 'exists:catalogo_bancos,id'],
            'aplica_saldo_favor' => ['nullable', 'boolean'],
            'saldo_a_favor' => ['nullable', 'numeric', 'min:0'],
            'saf_aplicaciones' => ['nullable', 'array'],
            'saf_aplicaciones.*.saf_credito_id' => ['required_with:saf_aplicaciones', 'integer', 'exists:saf_creditos,id'],
            'saf_aplicaciones.*.monto' => ['required_with:saf_aplicaciones', 'numeric', 'min:0.01'],
            'catalogo_tipo_caja_id' => ['nullable', 'exists:catalogo_tipos_caja_pedido,id'],
            'numero_cajas' => ['nullable', 'integer', 'min:0', 'max:999'],
            'peso_real_kg' => ['nullable', 'numeric', 'min:0'],
            'peso_cobrado_guia_kg' => ['nullable', 'numeric', 'min:0'],
            'catalogo_paqueteria_id' => ['nullable', 'exists:catalogo_paqueterias_pedido,id'],
            'catalogo_tipo_guia_id' => ['nullable', 'exists:catalogo_tipos_guia_pedido,id'],
            'catalogo_zona_id' => ['nullable', 'exists:catalogo_zonas_pedido,id'],
            'codigo_postal' => ['nullable', 'string', 'max:10'],
            'domicilio_entrega' => ['nullable', 'string'],
            'cliente_direccion_id' => ['nullable', 'integer', 'exists:cliente_direcciones,id'],
            'direccion_manual_excepcion' => ['nullable', 'boolean'],
            'motivo_direccion_manual' => ['nullable', 'string', 'max:500'],
            'direccion' => ['nullable', 'array'],
            'direccion.nombre_destinatario' => ['nullable', 'string', 'max:255'],
            'direccion.telefono_destinatario' => ['nullable', 'string', 'max:30'],
            'direccion.calle' => ['nullable', 'string', 'max:255'],
            'direccion.numero_exterior' => ['nullable', 'string', 'max:30'],
            'direccion.numero_interior' => ['nullable', 'string', 'max:30'],
            'direccion.colonia' => ['nullable', 'string', 'max:255'],
            'direccion.codigo_postal' => ['nullable', 'string', 'max:10'],
            'direccion.municipio' => ['nullable', 'string', 'max:255'],
            'direccion.ciudad' => ['nullable', 'string', 'max:255'],
            'direccion.estado' => ['nullable', 'string', 'max:255'],
            'direccion.pais' => ['nullable', 'string', 'max:255'],
            'direccion.referencias' => ['nullable', 'string', 'max:2000'],
            'direccion.indicaciones_entrega' => ['nullable', 'string', 'max:2000'],
            'direccion.domicilio_irregular' => ['nullable', 'boolean'],
            'envia_a_otra_persona' => ['nullable', 'boolean'],
            'envia_otra_persona' => [
                'nullable',
                'string',
                'max:255',
                Rule::requiredIf(fn () => filter_var($this->input('envia_a_otra_persona'), FILTER_VALIDATE_BOOLEAN)),
            ],
            'es_resguardo' => ['nullable', 'boolean'],
            'modo_resguardo' => ['nullable', 'in:abierto,complementario'],
            'pedido_principal_id' => [
                'nullable',
                'integer',
                'exists:pedidos_bma,id',
                'required_if:modo_resguardo,complementario',
            ],
            'anexar_remision' => ['nullable', 'boolean'],
            'total_mercancia' => ['nullable', 'numeric', 'min:0'],
            'costo_envio' => ['nullable', 'numeric', 'min:0'],
            'aplica_seguro' => ['nullable', 'boolean'],
            'cliente_proporciona_guia' => ['nullable', 'boolean'],
            'envio_por_cobrar' => ['nullable', 'boolean'],
            'costo_seguro' => ['nullable', 'numeric', 'min:0'],
            'cajas_costos' => ['nullable', 'array'],
            'cajas_costos.*.uuid_operativo' => ['required_with:cajas_costos', 'uuid'],
            'cajas_costos.*.costo_envio' => ['nullable', 'numeric', 'min:0'],
            'cajas_costos.*.costo_seguro' => ['nullable', 'numeric', 'min:0'],
            'cajas_costos.*.costo_adicional' => ['nullable', 'numeric', 'min:0'],
            'cajas_costos.*.concepto_adicional' => ['nullable', 'string', 'max:128'],
            'reabrir_pago_costos' => ['nullable', 'boolean'],
            'motivo_reapertura_pago' => ['nullable', 'string', 'min:5', 'max:2000'],
            'updated_at_esperado' => ['nullable', 'date'],
            'comentarios_drive' => ['nullable', 'string'],
            'comprobantes' => ['nullable', 'array'],
            'comprobantes.*' => ['file', 'image', 'max:10240'],
            'enviar' => ['nullable', 'boolean'],
        ];
    }
}
